#!/bin/bash

usage() {
    echo
    echo "Usage: hlwm-tag-groups/prompt [-p PROMPT] [-i INPUT-FILE] [-m MESSAGE] [-x EXCLUDE-OPTION]"
    echo
}

rofi=$(which rofi)

if [ "$rofi" -a -x "$rofi" ]; then
    exec $hlib/prompt-rofi "$@"
else
    echo "No interactive prompt option found"
    exit 1
fi
